# Generated by Django 3.2.14 on 2022-08-23 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='book_id',
        ),
    ]
