# Generated by Django 3.2.13 on 2023-02-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='', max_length=200)),
                ('deposite_cc_value', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='date published')),
            ],
            options={
                'ordering': ['user_id'],
            },
        ),
    ]
