# Generated by Django 3.2.14 on 2022-08-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('content', models.TextField(default='')),
                ('image_url', models.URLField(default='')),
                ('author_wallet', models.CharField(default='', max_length=200)),
                ('bookmark_img_url', models.URLField(default='')),
                ('curserial_number', models.CharField(default='', max_length=200)),
                ('datamine', models.CharField(default='', max_length=200)),
                ('origin_type_id', models.BigIntegerField(default=0)),
                ('book_type_id', models.BigIntegerField(default=0)),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='date published')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
