# Generated by Django 3.2.14 on 2022-08-07 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='bookmark_img_url',
            field=models.ImageField(upload_to='post_bookmark_images'),
        ),
        migrations.AlterField(
            model_name='books',
            name='image_url',
            field=models.ImageField(upload_to='post_main_images'),
        ),
    ]
