# Generated by Django 3.2.14 on 2022-08-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_books', '0002_auto_20220807_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='bookmark_img_url',
            field=models.ImageField(blank=True, null=True, upload_to='post_bookmark_images'),
        ),
        migrations.AlterField(
            model_name='books',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='post_main_images'),
        ),
    ]
