# Generated by Django 3.2.14 on 2022-08-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_books', '0003_auto_20220808_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_price',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='books',
            name='bookmark_price',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='books',
            name='hardbound',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='books',
            name='hardbound_from',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='books',
            name='hardbound_price',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='books',
            name='max_book_supply',
            field=models.BigIntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='books',
            name='max_bookmark_supply',
            field=models.BigIntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='books',
            name='start_point',
            field=models.BigIntegerField(default=1),
        ),
    ]
