# Generated by Django 3.2.14 on 2022-08-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_books', '0004_auto_20220823_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='introduction',
            field=models.TextField(default=''),
        ),
    ]
