# Generated by Django 3.2.14 on 2022-11-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_books', '0005_books_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='bm_contract_address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='books',
            name='bt_contract_address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='books',
            name='hb_contract_address',
            field=models.CharField(default='', max_length=200),
        ),
    ]
