# Generated by Django 3.2.14 on 2022-11-03 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_books', '0006_auto_20221103_0759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='bm_contract_address',
        ),
        migrations.RemoveField(
            model_name='books',
            name='bt_contract_address',
        ),
        migrations.RemoveField(
            model_name='books',
            name='hb_contract_address',
        ),
    ]
