# Generated by Django 3.2.14 on 2022-11-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_books', '0007_auto_20221103_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='hardbound',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='books',
            name='hardbound_from',
            field=models.CharField(default='', max_length=200),
        ),
    ]
