# Generated by Django 3.2.14 on 2022-11-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_books', '0009_auto_20221103_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='author_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
