# Generated by Django 3.2.14 on 2023-01-05 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_booktype', '0003_alter_booktype_options'),
        ('api_books', '0010_books_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_price',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_type_id',
            field=models.ForeignKey(db_column='book_type_id', default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='booktypes', to='api_booktype.booktype'),
        ),
        migrations.AlterField(
            model_name='books',
            name='bookmark_price',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
        migrations.AlterField(
            model_name='books',
            name='hardbound_price',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
    ]
