# Generated by Django 3.2.13 on 2023-01-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uploadimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadimage', models.ImageField(blank=True, null=True, upload_to='upload_images')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='date published')),
            ],
            options={
                'ordering': ['uploadimage'],
            },
        ),
    ]
