# Generated by Django 3.2.14 on 2022-08-04 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_booktype', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booktype',
            name='password',
        ),
        migrations.RemoveField(
            model_name='booktype',
            name='username',
        ),
        migrations.AddField(
            model_name='booktype',
            name='booktype',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='booktype',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, verbose_name='date published'),
        ),
    ]
