# Generated by Django 3.2.14 on 2022-08-04 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_booktype', '0002_auto_20220804_2256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booktype',
            options={'ordering': ['booktype']},
        ),
    ]
