# Generated by Django 3.2.13 on 2023-01-09 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_booktype', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('introduction', models.TextField(default='')),
                ('content', models.TextField(default='')),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='post_main_images')),
                ('author_name', models.CharField(default='', max_length=200)),
                ('author_wallet', models.CharField(default='', max_length=200)),
                ('bookmark_img_url', models.ImageField(blank=True, null=True, upload_to='post_bookmark_images')),
                ('curserial_number', models.CharField(default='', max_length=200)),
                ('datamine', models.CharField(default='', max_length=200)),
                ('origin_type_id', models.BigIntegerField(default=0)),
                ('max_bookmark_supply', models.BigIntegerField(default=-1)),
                ('max_book_supply', models.BigIntegerField(default=-1)),
                ('start_point', models.BigIntegerField(default=1)),
                ('book_price', models.DecimalField(decimal_places=3, max_digits=7)),
                ('bookmark_price', models.DecimalField(decimal_places=3, max_digits=7)),
                ('hardbound', models.CharField(default='', max_length=200)),
                ('hardbound_from', models.CharField(default='', max_length=200)),
                ('hardbound_price', models.DecimalField(decimal_places=3, max_digits=7)),
                ('bt_contract_address', models.CharField(default='', max_length=200)),
                ('hb_contract_address', models.CharField(default='', max_length=200)),
                ('bm_contract_address', models.CharField(default='', max_length=200)),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='date published')),
                ('book_type_id', models.ForeignKey(db_column='book_type_id', default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='booktypes', to='api_booktype.booktype')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
