# Generated by Django 3.2.13 on 2023-02-22 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_books', '0004_alter_books_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='start_point',
            new_name='book_from',
        ),
        migrations.RemoveField(
            model_name='books',
            name='hardbound',
        ),
        migrations.AddField(
            model_name='books',
            name='bookmark_from',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='books',
            name='max_hardbound_supply',
            field=models.BigIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='books',
            name='hardbound_from',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='books',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
