# Generated by Django 3.2.13 on 2023-02-24 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_books', '0006_bookmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarks',
            name='book_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book', to='api_books.books'),
        ),
    ]
