# Generated by Django 3.2.13 on 2023-02-24 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_books', '0007_bookmarks_book_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='bm_contract_address',
        ),
        migrations.RemoveField(
            model_name='books',
            name='bookmark_price',
        ),
        migrations.RemoveField(
            model_name='books',
            name='max_bookmark_supply',
        ),
        migrations.AlterField(
            model_name='bookmarks',
            name='book_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='api_books.books'),
        ),
    ]
