# Generated by Django 3.2.13 on 2023-03-07 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_books', '0014_auto_20230307_0030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='adcontent',
        ),
    ]
