# Generated by Django 3.2.13 on 2023-03-20 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_books', '0005_alter_books_user'),
        ('api_books', '0016_books_adcontent'),
    ]

    operations = [
    ]
