# Generated by Django 3.2.13 on 2023-04-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_books', '0017_auto_20230328_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_from',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='books',
            name='hardbound_from',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='books',
            name='max_book_supply',
            field=models.TextField(default='-1'),
        ),
        migrations.AlterField(
            model_name='books',
            name='max_hardbound_supply',
            field=models.TextField(default='-1'),
        ),
    ]
