# Generated by Django 3.2.13 on 2023-05-12 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_books', '0018_auto_20230424_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='byteperbookmark',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='books',
            name='adcontent',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='books',
            name='bm_listdata',
            field=models.JSONField(default=list),
        ),
    ]
