# Generated by Django 3.2.13 on 2023-02-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_authorinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorinfo',
            name='author_imageurl',
            field=models.ImageField(blank=True, null=True, upload_to='author_profile_images'),
        ),
    ]
