# Generated by Django 3.2.13 on 2023-02-17 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_authorinfo', '0002_alter_authorinfo_author_imageurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authorinfo',
            old_name='author_id',
            new_name='author',
        ),
    ]
